### ISSUE TITLE
Objects are not blocked on collision layer.

### ISSUE THREAD

**Issue by igorko** [Paul-Wortmann/Random_Map_Generator#7]
Objects should be blocked on collision layer.
For now I guess it would be enough to lock walking through but do not lock flying above (ignore object height differences).
This should be blue collision tile, if looking in Tiled. Not sure about index.

The best way would be add check here:

https://github.com/Paul-Wortmann/Random_Map_Generator/blob/master/src/MapGenerator.cpp#L191

If object was returned (not 0), block tile, otherwise do nothing on collision layer

**Comment by Paul-Wortmann** [comment]
Addressed in commit: 964a346f0b379831811b23ba61ea33f97c2f3438
There is currently no clear method of how to determine if an object can be flown over.
As such I have set all objects as fully impassable, until a better solution presents itself.
